
services:
  php-fpm:
    image: pusachev/php-fpm:8.4
    ports:
      - "9000:9000"
      - "9003:9003"
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
